repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff  # linter
        types_or: [ python, pyi, jupyter ]
        args: ["--fix", "--ignore=E501,F401"]
      - id: ruff-format  # formatter
        types_or: [ python, pyi, jupyter ]
